[1단계 - 자동차 경주] 김경근 미션 제출합니다.
hongik-dev-mentoring/java-racingcar pull request #1
Opened 2023-01-27 00:09 UTC by JuneK3

2023-01-28 04:26 UTC, skullkim requested changes
안녕하세요~ 김경근님😄. 첫 미션 어떠셨나요? 우선 일부 테스트와 계산기 미션만 리뷰를 했어요~ 피드백 수정 하면서 첨부한 글과 저희가 드린 공통 피드백 꼭 정독해주세요~. 그리고 제가 피드백 드린 내용은 피드백을 한 그 곳에서만 발생하고 있는 문제는 아니에요! 다른 코드에서도 발생하는 문제들이니 다른 곳도 같이 수정하고 제출해주세요😃. 그 후에 자동차 경주 피드백을 다시 드릴게요~

2023-01-28 04:26 UTC, skullkim commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
테스트들을 아주 세세하게 작성해주셨네요👍🏻. 그런대 하나의 테스트에서 여러 케이스를 검증할 때의 방식이 조금 잘못된거 같아요!. 아래 링크를 보시고 더 좋은 방법으로 수정해 보면 좋은거 같아요😄.
[Junit5 소개](https://www.skullkim-dev.com/2021/11/28/Junit5-%EC%86%8C%EA%B0%9C/)

2023-01-28 04:26 UTC, skullkim commented on src/test/java/calculator/CalculatorTest.java
> +        int actual = calculator.splitAndSum("");
테스트는 기능 검증이 최종 목적 중 하나죠. 그리고 그 검증을 위해서 assert문을 사용하고요. 즉, 모든 테스트의 끝은 assert로 끝나고 뒤에 추가 로직이 없어야 된다는 소리에요. 그래야 하나의 기능만 테스트 했다는 것을 명확히 할 수 있고, 가독성도 높아져요. 그런데 이 테스트는 하나의 assertThat 이후로 또 하나의 assertThat을 사용하고 있네요... 위에서 첨부한 'Junit5 소개' 링크를 보시고 개선해보면 좋을거 같아요!

2023-01-28 04:26 UTC, skullkim commented on src/test/java/calculator/CalculatorTest.java
> +    public void oneNumberStringInputTest() {
이 테스트도 개선해봐요!

2023-01-28 04:26 UTC, skullkim commented on src/test/java/calculator/CalculatorTest.java
> +//        int actual = calculator.splitAndSum("//;\n1:2:3");
필요 없는 주석은 반드시 지우고 커밋해주세요~

2023-01-28 04:26 UTC, skullkim commented on src/test/java/calculator/CalculatorTest.java
> +                .hasMessageContaining("음수는 계산할 수 없습니다.");
.hasMessageContaining()과 .hasMessage()는 어떤 차이가 있을까요? 어느 것을 사용하는게 더 좋을까요?

2023-01-28 04:26 UTC, skullkim commented on src/test/java/racingcar/CarTest.java
> +public class CarTest {
테스트는 문서의 역할을 해요. 그래서 읽는 사람이 테스트를 통해 어떤 기능이 있는지를 빠르게 파악할 수 있어야 하죠. 따라서 팀에서 영어를 사용하는 합의가 없었다면 한글로 테스트의 목적을 서술하는 것이 좋아요. CalculatorTest 처럼 @DisplayName() 어노테이션을 사용하거나 아예 메서드 이름을 한글로 명시해도 되요.

2023-01-28 04:26 UTC, skullkim commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.24.2'
assertJ 의존성이 있음에도 새로 추가한 이유가 있을까요?

2023-01-28 04:26 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +    private int calcuateOneNumberInputString(String input) {
오타는 꼭 확인하고 커밋해주세요~

2023-01-28 04:26 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +        if (CustomSeparatorExists(input)) {
나머지 두 검증은 테스트를 하지 않은 반면, CustomSepraratorExists()는 테스트를 한 이유가 있을까요? 그리고 메서드 이름의 시작은 대문자가 아닌 소문자로 해주세요~

2023-01-28 04:26 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +    }
조건문 조건에서 호출하는 메서드들이 같은 클래스 내에 중구난방으로 펴져있는대 이러면 해당 메서드들을 파악하기 위해 클래스의 여러 부분들을 왔다 갔다 해야 되서 혼란을 야기해요.
[클린코드 챕터 5. 형식 맞추기](https://www.skullkim-dev.com/2022/01/13/5.-%ED%98%95%EC%8B%9D-%EB%A7%9E%EC%B6%94%EA%B8%B0/) 에서 '세로 밀집도' ~ '세로 순서' 부분을 모두 읽어보세요~

단지 테스트를 위해 private으로 두어야 하는 메서드를 public으로 두는 것은 좋지 않아요. private으로 두어야 하는 메서드는 어떤 의미를 가질까요? 유닛이 맞을까요?

```suggestion
    public int splitAndSum(String input) {
        if (isInputNullOrEmpty(input)) {
            return 0;
        }
        if (CustomSeparatorExists(input)) {
            return calculateWithCustomDelimiter(input);
        }
        if (isInputOneNumberString(input)) {
            return calcuateOneNumberInputString(input);
        }
        return calculateWithDefaultSeparator(input);
    }
```

2023-01-28 04:26 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +            tokens = m.group(2).split(customDelimiter);
여러 메서드를 묶어서 호출하는 것을 메서드 체이닝이라 하는대요. 이 경우 m.group(2).split(customDelimiter)가 메서드 체이닝에 해당해요. 메서드 체이닝이 발생했을 때는 하나의 메서드 호출만 한 줄에 두는 것이 가독성에 좋아요.
```java
tokens = m.group(2)
    .split(customDelimiter);
```

의미 있는 변수명을 사용해 주세요. 코드는 작성하고 끝이 아니라 나중에 자신을 포함한 누군가는 반드시 읽어야 하는 글입니다. 그리고 매직 넘저를 사용하는 대신 상수를 사용해주세요. 숫자는 그 자체로 어떤 의미인지 알 수 없습니다. 
[클린코드 chapter 2. 의미 있는 이름](https://www.skullkim-dev.com/2022/01/02/2.-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84/)을 참고해 주세요.

2023-01-28 05:16 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +    }
'세로 밀집도' ~ '세로 순서' 부분을 읽고 나서 생각한 개선방법은 호출되는 순서대로 함수들을 배치하는 것인데 윤기님이 의도하신 부분이 맞을까요?
이렇게 되면 클래스의 여러부분을 왔다갔다 하지 않아도 될 것 같아서 가독성이 많이 좋아질 것 같아요.

2023-01-28 05:16 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +    }
테스트를 위해 private으로 두어야 하는 메서드를 public으로 두는 것은 좋지 않다고 하신 부분을 개선하려고 스스로 생각해봤는데 많이 어렵게 느껴져지더라구요. 구글링으로 관련된 좋은 글을 찾아 읽어보고 개선방안을 알게 되었어요.
링크: https://mangkyu.tistory.com/235

private 메소드를 테스트하기 위해 public으로 두는 방식은 잘못된 것 같아요.
public으로 두지 않고 reflection을 이용해 테스트하는 방식이 있더라구요.
하지만 reflection을 이용해 private 메소드를 테스트하는 것을 지양해야 할 것 같아요.

private으로 두어야 하는 메서드는 유닛에 포함하지 않고
private 메소드를 호출하는 public 메소드로 private 메소드 로직을 테스트해야 할 것 같은데 이 방식이 맞을까요?

2023-01-28 05:21 UTC, JuneK3 commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
하나의 테스트에서 여러 케이스를 검증할 때의 방식이 잘못된거 같다고 말해주셨는데
아래에 comment로 리뷰해주신 내용들에 해당되는 걸까요??

그게 아니라면 `하나의 테스트에서 여러 케이스를 검증할 때의 방식`에 대해서 구체적인 설명을 들을 수 있을까요?
올려주신 링크를 읽어보고 왔는데 지금 제 실력으로는 잘못된 방식들이 바로 와닿지 않더라구요.

2023-01-28 05:33 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +            tokens = m.group(2).split(customDelimiter);
매직 넘버를 사용하는 대신 상수를 사용하는 건 아래처럼 작성하는 방식에 해당할까요?
이런식으로 값을 관리하면 다른 사람이 읽었을때 숫자의 의미를 파악하기 쉬울 것 같아요.
``` java
public enum Rule {
    MIN_SPEED(0),
    MAX_SPEED(9),
    ABLE_TO_ACCELERATE(4),
    MAX_NAME_LENGTH(5),
    MIN_NAME_LENGTH(1),
    CAR_NAME_SEPARATOR(","),
    CAR_IN_LAPSE_SEPARATOR(" : "),
    CAR_DRIVEN_DISTANCE_GAUGE("-"),
    BLANK(" ");

    private int constant;
    private String separator;

    Rule(int constant) {
        this.constant = constant;
    }

    Rule(String separator) {
        this.separator = separator;
    }

}
```

2023-01-30 06:08 UTC, skullkim requested changes
김경근님~ 수정해주신 부분 잘 확인했습니다!. 추가 코멘트를 남겼으니 그 부분도 추가 수정 해주세요😃. 그리고 제가 남긴 코멘트에 경근님의 의견을 꼭 남겨주세요. 일부 코멘트에는 경근님의 생각을 답변해 주셔야 하는대 답변이 안되 있는 부분이 있네요.

2023-01-30 06:08 UTC, skullkim commented on src/test/java/calculator/CalculatorTest.java
> +public class CalculatorTest {
하나의 테스트에서 assert는 테스트에서 가장 마지막에 들어와야 하고, 여러 테스트를 검증하는 방식도 잘못되었다는 의미였어요~ 잘 수정해주셨네요👍🏻

2023-01-30 06:08 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +    }
맞아요😄

2023-01-30 06:08 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +            tokens = m.group(2).split(customDelimiter);
상수를 사용하면 다른 사람이 의도를 명확히 파악할 수 있어서 사용하는게 맞아요. 그런대 모든 상수를 별도의 클래스에 모아놓으셨네요? 객체에서 필드는 어떤 의미를 가질까요? 객체가 가져야 하는 책임은 어디까지일까요?

2023-01-30 06:08 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +        String s = input.replaceAll(NON_DIGIT_CHARACTER_PATTERN, BLANK)
[클린코드 2장. 의미 있는 이름](https://www.skullkim-dev.com/2022/01/02/2.-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84/)을 참고해서 변수 이름을 바꾸어 보는게 어떨까요?

2023-01-30 06:08 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +                .reduce(INITIAL_VALUE_OF_SUM, (a, b) -> a + b);
이 방식은 어떨까요? [모던 자바 인 액션 3장. 람다 표현식](https://www.skullkim-dev.com/2022/02/14/3%EC%9E%A5.-%EB%9E%8C%EB%8B%A4-%ED%91%9C%ED%98%84%EC%8B%9D/)을 참고해 주세요~
```suggestion
                .reduce(INITIAL_VALUE_OF_SUM, Integer::sum);
```

2023-01-30 06:08 UTC, skullkim commented on src/main/java/racingcar/Car.java
> +    public void move() {
이 메서드에 대한 테스트가 없네요? 이 메서드는 어떻게 테스트할 수 있을까요?

2023-01-30 06:08 UTC, skullkim commented on src/main/java/racingcar/Race.java
> +                .max(Comparator.comparing(Car::getPosition))
max()는 Optional을 반환하고 있는대요. Optional은 무엇이고 get()을 사용하면 안되는 이유는 무엇일까요?
[모던 자바 인 액션 11장. null 대신 Optinal 클래스](https://www.skullkim-dev.com/2022/03/27/11%EC%9E%A5.-null-%EB%8C%80%EC%8B%A0-Optional-%ED%81%B4%EB%9E%98%EC%8A%A4/) 를 참고해 주세요.

2023-01-30 06:08 UTC, skullkim commented on src/main/java/racingcar/Race.java
> +        return winners;
바로 반환하는건 어떤가요?
```suggestion
        return cars.stream()
                .filter(car -> car.getPosition().equals(maxPosition))
                .collect(Collectors.toList());
```

2023-01-30 06:08 UTC, skullkim commented on src/main/java/racingcar/Race.java
> +        System.out.println(sb);
이건 어떨까요?
```suggestion
 List<String> winnerNames = winners.stream()
                .map(Car::getName)
                .collect(Collectors.toList());
 System.out.println(String.join(COMMA_IN_RESULT_TEXT, winnerNames));
```

2023-01-30 06:08 UTC, skullkim commented on src/main/java/racingcar/input/Validation.java
> +        if (!(CAR_NAME_MIN_LIMIT <= length && length <= CAR_NAME_MAX_LIMIT)) {
조건이 너무 길어지면 해당 조건이 어떤 것을의미하는지 파악하는대 시간이 오래걸리는대요. 조건 부분만 별도의 메서드로 떼어 놓는건 어떤가요?

2023-01-30 06:08 UTC, skullkim commented on src/main/java/racingcar/input/Validation.java
> +            throw (new IllegalArgumentException(DUPLICATED_NAMES));
이 예외만 괄호로 묶은 이유가 있을까요?

2023-01-30 07:05 UTC, merged

2023-01-30 08:16 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +                .reduce(INITIAL_VALUE_OF_SUM, (a, b) -> a + b);
이런식으로도 쓸 수 있군요. 알려주신 방식이 훨씬 간결하고 알기 쉬운 것 같아요.
올려주신 블로그 링크도 읽어볼게요.

2023-01-30 08:18 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +        String s = input.replaceAll(NON_DIGIT_CHARACTER_PATTERN, BLANK)
아 질문주신부분은 혼자 고민하고 답을 찾기만 했는데 앞으로는 잊지않고 답변 남겨놓을게요.

2023-01-30 08:23 UTC, JuneK3 commented on src/main/java/racingcar/Car.java
> +    public void move() {
난수를 생성하는 로직을 테스트하려고 나름대로 고민을 많이 해봤는데 제 실력으로는 마땅한 방법이 떠오르지가 않더라구요. 난수 생성 같은 로직은 굳이 테스트를 하지 않아도 된다는 글을 읽은 기억이 있어서 고민하다가 그냥 넘긴것 같아요, 다시 구글링도 해보고 적절한 방법을 찾아볼게요.

혹시 참고할만한 자료를 알고 계시면 링크를 알려주실 수 있을까요? 일단 제 나름대로 답을 찾아보겠습니다.

2023-01-30 08:25 UTC, JuneK3 commented on src/main/java/racingcar/Race.java
> +        return winners;
변수로 분리해서 return하는 방식이 가독성이 좋을 것 같다는 생각에 이렇게 작성했던 것 같아요.
다시 생각해보니 바로 return하는 방식이 더 간결하고 깔끔한 것 같아요.

2023-01-30 08:27 UTC, JuneK3 commented on src/main/java/racingcar/Race.java
> +        System.out.println(sb);
이 코드를 작성하면서 분명 더 좋은 방식이 있을 것 같아서 계속 고민하고 있었는데
join 메소드를 사용하면 간단히 해결되는 문제였네요.. 많이 배웠습니다.

2023-01-30 08:27 UTC, JuneK3 commented on src/main/java/racingcar/input/Validation.java
> +        if (!(CAR_NAME_MIN_LIMIT <= length && length <= CAR_NAME_MAX_LIMIT)) {
확실히 조건 부분을 메소드로 분리하는게 가독성이 훨씬 좋을 것 같아요. 바로 수정하겠습니다.

2023-01-30 08:28 UTC, JuneK3 commented on src/main/java/racingcar/input/Validation.java
> +            throw (new IllegalArgumentException(DUPLICATED_NAMES));
이 부분은 제가 놓친 오타인 것 같아요. 바로 수정해놓겠습니다.

2023-01-30 08:44 UTC, JuneK3 commented on src/main/java/racingcar/Race.java
> +                .max(Comparator.comparing(Car::getPosition))
Optional은 null 값이 될 수 있는 값을 감싸는 wrapper 클래스이고 Optional을 통해 NPE를 방지할 수 있어요.
get()을 사용하려면 Optional 객체에 null이 아닌 값이 존재하는지 반드시 확인해야 하는 걸로 알고 있어요.
그렇게 하지 않고 바로 get()을 사용하면 NPE을 방지할 수 없으니 Optional을 사용하지 않는 것과 다를게 없을 거에요.

혹시 의도하신 답이 이게 맞을까요? ifPresent()와 get()을 같이 사용하는 방식도 피해야 할까요?

2023-01-30 08:47 UTC, JuneK3 commented on src/test/java/calculator/CalculatorTest.java
> +                .hasMessageContaining("음수는 계산할 수 없습니다.");
메시지의 일부를 포함하는지 테스트하는 경우에는 hasMessageContaining()를 사용하고
메시지 자체로 테스트하는 경우에는 hasMessage()를 사용하는게 좋을 것 같아요.
제 코드의 경우 hasMessage()를 사용하는게 더 나을 것 같아요.

2023-01-30 08:47 UTC, JuneK3 commented on build.gradle
> +    testImplementation 'org.assertj:assertj-core:3.24.2'
제가 주의 깊게 build.gradle을 살펴보지 않았네요.. 바로 수정했습니다.

2023-01-30 08:50 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +        if (CustomSeparatorExists(input)) {
제가 customSepraratorExists()로 분리한 로직을 테스트하려고 임의로 작성했던 코드일거에요.
customSepraratorExists()도 접근제어자를 private으로 바꾸고 customSepraratorExists를 호출하는 메소드를 테스트하도록 수정해야 할 것 같아요. 메소드 이름도 제대로 수정했습니다.

2023-01-30 10:26 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +        String s = input.replaceAll(NON_DIGIT_CHARACTER_PATTERN, BLANK)
변수 s는 이름을 바꿀 필요가 있는 것 같아요. 적절한 이름으로 수정하겠습니다.

2023-01-30 11:42 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +            tokens = m.group(2).split(customDelimiter);
여러 클래스들이 같이 사용하는 상수가 있다보니 따로 상수 클래스를 만들어서 관리하려 했던 것 같아요.
객체의 필드는 객체가 담당하는 역할을 수행하기 위해 필요한 정보들을 저장하는 역할을 한다고 생각해요.
객체가 맡은 역할을 수행하는 것이 객체가 가지는 책임인 것 같아요. 

상수를 별도의 클래스로 모으게 되면 객체의 역할과 책임이 적절하게 나뉘지 못하는 것 같아요.
객체가 역할을 수행하기 위해 필요한 필드가 상수 클래스에 존재하기 때문에 불필요한 의존이 생기게 되는 것 같아요.
클래스별로 상수를 필드로 관리하도록 변경해볼게요.

2023-01-30 11:44 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +            tokens = m.group(2).split(customDelimiter);
제가 제대로 생각한게 맞는지 잘 모르겠네요.
객체에서 필드가 갖는 의미와 객체가 가지는 책임에 대해서는 좀 더 고민해봐야 할 것 같아요.

2023-01-30 13:41 UTC, JuneK3 commented on src/main/java/racingcar/Car.java
> +    public void move() {
난수 생성 로직을 분리하면 테스트가 가능할 것 같아요.
2단계에서는 난수 생성 로직을 분리해서 테스트 해보겠습니다.

2023-02-04 04:13 UTC, skullkim commented on src/main/java/racingcar/Race.java
> +                .max(Comparator.comparing(Car::getPosition))
네! 맞아요. ifPresent()와 get()을 같이 사용하는 것은 괜찮아요. 하지만 이 둘을 같이 사용한다는 것은 조건문의 조건으로 ifPResent()를 사용한다는 의미겠죠? 그리고 ifPresent()일 때와 아닐 때의 로직을 나누겠다는 의미일거고요. 그러면 Optional에서 제공하는 다른 메서드로 이 목적을 더 짧고 간결하게 달성할 수 있지 않을까요?

2023-02-04 10:35 UTC, JuneK3 commented on src/main/java/racingcar/Race.java
> +                .max(Comparator.comparing(Car::getPosition))
확실히 ifPresent()와 get()을 같이 사용하지 않고 Optional에서 제공하는 다른 메서드를 사용하는게 훨씬 간결한 것 같아요.
불필요한 조건문을 작성하지 않아도 되니 코드도 짧아지겠네요. 앞으로는 무분별한 get() 호출을 지양해야겠어요.