[1단계 - 자동차경주] 이태순 미션 제출합니다
hongik-dev-mentoring/java-racingcar pull request #2
Opened 2023-01-27 02:54 UTC by LTSGOD

2023-01-27 11:30 UTC, dongho108 requested changes
안녕하세요 태순님! 첫번째 과제 진행하느라 고생 많으셨습니다~ 😂

컨벤션을 전체적으로 다시한번 보실 필요가 있을 것 같구요!
readme를 수정하실 땐 커밋 메세지 컨벤션을 적용하지 않으셨더라구요. 특별한 이유가 있으실까요?

그리고 문자열 계산기 코드들은 src/java/main 안에서 패키지로 Car 미션과 구분해주시면 소스코드로 인식이 잘 될거같아서 그렇게 고쳐주시고 다시 리뷰요청 부탁드립니다~!

2023-01-27 11:30 UTC, dongho108 commented on java-stringcalculater/src/main/java/StringCalculator.java
> +public class StringCalculator {
계산기 코드들은 src/main/java/ 안에서 패키지로 구분해주세요! 바깥에 있어서 소스코드로 인식을 못하고 있네요.

2023-01-27 11:30 UTC, dongho108 commented on java-stringcalculater/src/test/java/StringCalculatorTest.java
> +
필요없는 줄바꿈은 삭제해주세요

2023-01-27 11:30 UTC, dongho108 commented on java-stringcalculater/src/test/java/StringCalculatorTest.java
> +	public void splitAndSum_null_또는_빈문자() throws Exception {
커밋상으로 모든 테스트를 한번에 만들고 커밋하신것 처럼 보이는데, 테스트 하나마다 동작하는 코드를 하나씩 만들어 주세요! 그리고 커밋은 기능단위로, 컴파일 및 실행이 가능한 상태일때 커밋해야 언제든 해당 커밋으로 돌아가도 문제가 없겠죠?

2023-01-27 11:30 UTC, dongho108 commented on java-stringcalculater/build.gradle
> +plugins {
계산기 관련 클래스들이 옮겨진다면 계산기 관련 코드의 설정 파일들이 있을필요가 없어지겠네요

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Car.java
> +	}//Test용
필요없는 주석은 제거해주세요.

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Car.java
> +	}
필요없는 주석은 제거해주세요. 주석보다는 코드에서 의미를 알아볼 수 있게 작성해주세요!

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Car.java
> +		return (int)(Math.random()*10);
매직넘버를 사용하고 있네요 상수로 뺄 수 있을까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Car.java
> +	private final int MOVE = 4;
MOVE 는 Car 객체의 인스턴스 변수인가요 상수인가요? 만약 상수로 사용하는데 static으로 선언하지 않는다면 어떤 문제가 발생할까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Car.java
> +	public boolean move() {
move()는 내부에서만 사용하는 메서드처럼 보이는데 public으로 선언하신 이유가 있을까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Game.java
> +		//최종결과
사용하지 않는 주석은 제거해주세요!

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Game.java
> +		System.out.println("실행 결과\n");
불필요한 코드는 제거해주세요

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Game.java
> +	private static int tryNum;
상수 네이밍 규칙은 대문자입니다! 그리고 변하지 않는다면 final 키워드를 붙여주는 것이 어떨까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Game.java
> +	private static List<Car> cars;
cars 에 static을 붙여주신 이유가 있을까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Game.java
> +public class Game {
Game 클래스 안의 메서드들은 전부 static으로 되어있는데 static 을 붙여준 이유가 있을까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +		while(true){
공백도 컨벤션 입니다.

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +		while(true){
while(true) 에서는 어떤 문제가 발생할 수 있을까요?

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +	private static int tryNum;
상수 네이밍 규칙!

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +		while(true){
공백도 컨벤션 입니다.

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +		}catch(Exception e){
공백도 컨벤션 입니다.

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +		}catch(IllegalArgumentException e){
공백도 컨벤션 입니다.

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/Input.java
> +	private static boolean noExceptionAtNum(String input) {
메서드 명이 동사로 시작하지 않고있어요

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/InputException.java
> +		if(input.isEmpty()) throw new IllegalArgumentException("이름을 입력해주세요.");
공백 컨벤션 다시한번 살펴보시고 전체적으로 수정 부탁드려요~

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/InputException.java
> +	private static final int MAX_LENGTH = 5;
여기는 상수 네이밍 규칙과 선언을 잘 해주셨네요! 💯

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/InputException.java
> +	}
메서드 명이 동사로 시작하지 않고 있네요~

2023-01-27 11:30 UTC, dongho108 commented on src/main/java/InputException.java
> +		if(input == null) throw new IllegalArgumentException("다시 입력해주세요.");
if 문은 한줄로 줄여쓰지 않는것도 컨벤션입니다!

2023-01-27 11:30 UTC, dongho108 commented on src/test/java/CarTest.java
> +
불필요한 줄바꿈으 지워주세요

2023-01-27 11:30 UTC, dongho108 commented on src/test/java/GameTest.java
> +}
파일의 마지막 줄에는 eof 도 컨벤션입니다!
eof : https://en.wikipedia.org/wiki/End-of-file

2023-01-29 09:57 UTC, LTSGOD commented on src/main/java/Car.java
> +	private final int MOVE = 4;
상수인데 static으로 선언하지 않으면 객체마다 변수가 할당되어서 메모리 낭비가 일어나는 문제가 있다고 생각을 했는데 제가 생각한 문제가 발생하는게 맞나요??

2023-01-29 09:57 UTC, LTSGOD commented on src/main/java/Car.java
> +	private final int MOVE = 4;
> MOVE 는 Car 객체의 인스턴스 변수인가요 상수인가요? 만약 상수로 사용하는데 static으로 선언하지 않는다면 어떤 문제가 발생할까요?

상수인데 static으로 선언하지 않으면 객체마다 변수가 할당되어서 메모리 낭비가 일어나는 문제가 있다고 생각을 했는데 제가 생각한 문제가 발생하는게 맞나요??

2023-01-29 09:58 UTC, LTSGOD commented on java-stringcalculater/src/test/java/StringCalculatorTest.java
> +	public void splitAndSum_null_또는_빈문자() throws Exception {
넵!!  하나마다 동작하게 코드 작성하겠습니다

2023-01-29 10:40 UTC, LTSGOD commented on src/main/java/Car.java
> +	public boolean move() {
원래는 Car 객체 내부에서만 사용하기 때문에 private으로 선언을 했었는데 그렇게 되면 단위테스트에서 move()라는 메서드를 호출할수가 없어서 테스트를 위해 public으로 선언했었는데요! 이런 경우에는 어떤식으로 접근을 선언해야할까요??

2023-01-29 10:49 UTC, LTSGOD commented on src/main/java/Game.java
> +public class Game {
테스트 코드를 작성할 때 Game 의 메서드를 객체 생성없이 호출하기 위해 static을 붙여주었었는데 이는 좋은 방법이 아닌지 궁금합니다!

2023-01-29 10:52 UTC, LTSGOD commented on src/main/java/Input.java
> +		while(true){
들여쓰기의 depth가 1이 넘어가서 조건을 지키지 못한건가요??

2023-01-29 11:07 UTC, LTSGOD commented on src/test/java/GameTest.java
> +}
네! 그러면 파일끝에 enter한 번씩 치면 되는게 맞나요??

2023-01-29 11:30 UTC, LTSGOD commented
> 안녕하세요 태순님! 첫번째 과제 진행하느라 고생 많으셨습니다~ 😂
> 
> 컨벤션을 전체적으로 다시한번 보실 필요가 있을 것 같구요! readme를 수정하실 땐 커밋 메세지 컨벤션을 적용하지 않으셨더라구요. 특별한 이유가 있으실까요?
> 
> 그리고 문자열 계산기 코드들은 src/main/java 안에서 패키지로 Car 미션과 구분해주시면 소스코드로 인식이 잘 될거같아서 그렇게 고쳐주시고 다시 리뷰요청 부탁드립니다~!

다음부터 readme도 커밋메세지 컨벤션 적용하도록 하겠습니다!

2023-01-30 07:20 UTC, dongho108 approved these changes
태순님 1단계 진행하시느라 정말 고생 많으셨습니다~~!
질문 주신것들에 대한 답변 남겨놓았구요. 몇가지 리뷰가 추가되었으니까 확인 한번 부탁드리고 2단계에서 반영해주시면 됩니다!

2단계에서 뵙겠습니다!

2023-01-30 07:20 UTC, dongho108 commented on src/main/java/Car.java
> +	public boolean move() {
단순히 테스트를 위해서 접근제어자를 바꾸는건 테스트 클래스가 내부 메소드 구조를 알고있으니 결합도가 높아지고 깨지기 쉬운 테스트코드가 됩니다. private 메서드를 테스트하는 상황이라면 설계가 잘못되진 않았는지 점검해볼 필요가 있습니다.

2023-01-30 07:20 UTC, dongho108 commented on src/main/java/Game.java
> +public class Game {
테스트 코드를 작성할때 메서드를 객체 생성없이 호출할 필요가 있을까요?

2023-01-30 07:20 UTC, dongho108 commented on src/main/java/Car.java
> +	}
setter를 제거합시다!
객체의 데이터를 마음대로 변경할 수 있는 것은 가독성을 해치고 유지보수가 어려운 코드가 될 수 있습니다.
데이터 변경하는 메서드가 필요할땐 메서드 명으로 의도를 드러내며 객체에게 책임을 주세요!

2023-01-30 07:20 UTC, dongho108 commented on src/main/java/RacingCarInputException.java
> +			throw new IllegalArgumentException("이름을 입력해주세요.");
if문에서 `{}` 중괄호는 항상 달아주는 것도 컨벤션입니다!
전체적으로 점검 한번 해주세요!

2023-01-30 07:20 UTC, dongho108 commented on src/main/java/Car.java
> +	private final int MOVE = 4;
맞습니다~

2023-01-30 07:20 UTC, dongho108 commented on src/test/java/GameTest.java
> +}
넵~

2023-01-30 07:20 UTC, dongho108 commented on src/main/java/Input.java
> +		while(true){
아뇨 depth는 잘 지켜주셨습니다~
다른 방식으로 변경 요청드리는 것은 아니고 while(true) 조건에서 어떤 문제가 발생할 수 있는지 짚어주기 위한 의도였습니다!

2023-01-30 07:20 UTC, merged

2023-01-30 10:03 UTC, LTSGOD commented on src/main/java/Game.java
> +public class Game {
아 넵! 생각을 잘 못 했던것 같아요 피드백 반영해서 수정해보겠습니다.

2023-01-30 10:04 UTC, LTSGOD commented on src/main/java/Input.java
> +		while(true){
조건을 잘 맞추지 않으면 무한루프를 돌 가능성이 있는 것이 맞나요??