[1단계 - 자동차경주] 이진호 미션 제출합니다.
hongik-dev-mentoring/java-racingcar pull request #4
Opened 2023-01-27 08:47 UTC by binary-ho

2023-01-27 12:19 UTC, dongho108 requested changes
안녕하세요 진호님!! 첫 미션 제출 하느라 고생 많으셨습니다 ㅎㅎ

코드 생각보다 깔끔하게 짜주시고 컨벤션도 맞추려고 노력해주신 모습이 보여서 좋았습니다.

리뷰는 진호님이 구현하실때의 생각을 묻는 부분들과 컨벤션을 중심으로 진행했습니다. 차근차근 답변해주시고 리뷰도 반영해주시면 좋을 것 같아요!

**참고**
고민되는 부분, 중점적으로 리뷰를 받고싶은 부분은 PR 을 제출할때 적는 칸에다가 간략하게 적어주시면 리뷰에도 도움이되고 다음에 복습하실때도 유용하게 쓰실 수 있습니다~

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/calculator/StringCalculator.java
> +}
파일의 맨 마지막 eof도 컨벤션입니다~
https://naver.github.io/hackday-conventions-java/

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/CarRacingController.java
> +        RangedRandomNumberPicker rangedRandomNumberPicker = new RangedRandomNumberPicker(0, 9);
매직넘버는 상수로 빼주세요!

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/Racing.java
> +//        winnerString.setLength(winnerString.length() - 2);
필요없는 주석은 지워주세요~

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/Racing.java
> +    public final List<Car> cars;
Racing 내부에서만 사용하는 변수인데 public으로 선언해놓으신 이유가 있을까요?

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/RangedRandomNumberPicker.java
> +    private final int from, to;
하나의 선언문에는 하나의 변수만 선언해 주는 것도 컨벤션입니다~
(네이버 핵데이 컨벤션 3.6. 참고)

2023-01-27 12:19 UTC, dongho108 commented on src/test/java/calculator/StringCalculatorTest.java
> +}
파일 맨끝에 줄바꿈 추가해주세요~

2023-01-27 12:19 UTC, dongho108 commented on src/test/java/racingcar/CarTest.java
> +    @RepeatedTest(REPEAT)
RepeatedTest 를 사용하신 이유가 있을까요?

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/Car.java
> +    public void printCurrentPosition();
인터페이스의 모든 메서드는 public abstract로 선언되어야 하며 이 키워드가 없어도 자동으로 적용되어 생략이 가능합니다~

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/Input.java
> +public class Input {
Input 객체에서 사용하는 메서드들은 static으로 선언되면 사용할때마다 클래스의 인스턴스를 생성하지 않아도 될거같은데 진호님 생각은 어떠신가요?

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/Car.java
> +public interface Car {
Car를 interface로 선언해주신 이유가 있을까요?

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/RandomMovingCar.java
> +    private final int STANDARD_CAN_MOVING = 4;
상수는 static 으로 선언해주시는게 어떨까요?

2023-01-27 12:19 UTC, dongho108 commented on src/main/java/racingcar/RandomMovingCar.java
> +    private final StringBuilder currentPositionString;
이 필드는 RandomMovingCar가 꼭 들고있어야 하는 필드인가요?

2023-01-27 12:19 UTC, dongho108 commented on src/test/java/racingcar/CarTest.java
> +}
만약 RandomMovingCar 객체 안의 StandardNumber가 바뀌게 된다면 어떻게 될까요?

2023-01-27 12:19 UTC, dongho108 commented on src/test/java/racingcar/RacingTest.java
> +public class RacingTest {
테스트코드에서 프린트문이 있을 필요가 있을까요?

2023-01-27 12:48 UTC, dongho108 commented on src/main/java/racingcar/Application.java
> +    public static void main(String[] args) {
음수를 입력받았을때의 예외처리는 안하신 이유가 있나요?

2023-01-29 20:56 UTC, binary-ho commented on src/main/java/calculator/StringCalculator.java
> +}
반영했습니다. 섬세한 리뷰 감사합니다.

2023-01-29 20:57 UTC, binary-ho commented on src/main/java/racingcar/CarRacingController.java
> +        RangedRandomNumberPicker rangedRandomNumberPicker = new RangedRandomNumberPicker(0, 9);
확인했습니다. 섬세한 리뷰 감사합니다.

2023-01-29 20:57 UTC, binary-ho commented on src/main/java/racingcar/Racing.java
> +//        winnerString.setLength(winnerString.length() - 2);
부끄럽네요 반영했습니다. 감사합니다!

2023-01-29 20:57 UTC, binary-ho commented on src/main/java/racingcar/Racing.java
> +    public final List<Car> cars;
미처 확인하지 못 했습니다. 감사합니다.

2023-01-29 20:58 UTC, binary-ho commented on src/main/java/racingcar/RangedRandomNumberPicker.java
> +    private final int from, to;
놓친 부분 자세히 봐주셔서 감사합니다. 수정했습니다.

2023-01-29 20:59 UTC, binary-ho commented on src/main/java/racingcar/Car.java
> +public interface Car {
관성적으로 인터페이스로 작성했습니다.
지금 생각해보니 왜 그랬는지 모르겠습니다.

2023-01-29 20:59 UTC, binary-ho commented on src/main/java/racingcar/RandomMovingCar.java
> +    private final int STANDARD_CAN_MOVING = 4;
확인했습니다. 감사합니다!

2023-01-29 21:01 UTC, binary-ho commented on src/main/java/racingcar/RandomMovingCar.java
> +    private final StringBuilder currentPositionString;
의도는 자동차의 현재 위치를 출력하는 방식은 자동차 클래스가 직접 결정하도록 해주는 것이였습니다.
지금 생각해보니, 자동차는 자동차 역할에만 충실하는게 좋을것 같고 포지션 접근자도 있는 마당에 굳이 그럴 필요가 없을 것 같네요!

2023-01-29 21:01 UTC, binary-ho commented on src/test/java/racingcar/CarTest.java
> +}
미처 생각하지 못 했습니다. 기준점을 상수화 시켜서 테스트에서 사용하도록 반영했습니다 감사합니다.

2023-01-29 21:02 UTC, binary-ho commented on src/test/java/racingcar/RacingTest.java
> +public class RacingTest {
출력 테스트 과정에서 넣었습니다. 전부 빼주었습니다. 감사합니다!

2023-01-29 21:03 UTC, binary-ho commented on src/main/java/racingcar/Application.java
> +    public static void main(String[] args) {
명세를 놓치다니 너무 큰 잘못을 저질렀네요. 예외상황 처리 구현했습니다 감사합니다.

2023-01-30 07:34 UTC, dongho108 approved these changes
진호님 1단계 미션 구현하느라 고생 많으셨습니다~
여기서 일단 머지하고 추가로 남긴 리뷰는 2단계에서 반영해주세요!
다음 단계에서 뵙겠습니다 🙇

2023-01-30 07:34 UTC, dongho108 commented on src/main/java/racingcar/CarRacingController.java
> +        RangedRandomNumberPicker rangedRandomNumberPicker = new RangedRandomNumberPicker(0, 9);
이 부분 반영해주셨나요?

2023-01-30 07:34 UTC, dongho108 commented on src/main/java/racingcar/RandomMovingCar.java
> +    public static final int MOVING_STANDARD = 4;
캡슐화가 잘 지켜졌다고 볼 수 있을까요?

2023-01-30 07:34 UTC, dongho108 commented on src/main/java/racingcar/RandomMovingCar.java
> +    public static final int MOVING_STANDARD = 4;
랜덤을 테스트 하기 힘들어서 이런 구조가 나온것 같습니다 ㅎㅎ 2단계에서 캡슐화와 랜덤테스트를 같이 할 수 있는 방법을 고민해봅시다!

2023-01-30 07:34 UTC, merged