[2단계 - 자동차 경주] 김경근 미션 제출합니다.
hongik-dev-mentoring/java-racingcar pull request #5
Opened 2023-02-01 08:51 UTC by JuneK3

2023-02-05 07:00 UTC, skullkim requested changes
안녕하세요~ 경근님~. 미션은 어떠신가요😄? 추가 리뷰 남겼어요~

2023-02-05 07:00 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +
splitCustomInputAndParseToInt() 내부에 m이라는 변수이름을 좀 더 의미있는 이름으로 바꾸어주세요~

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/Application.java
> +        raceController.startRace();
main 메서드에서는 RaceController의 메서드 하나만 호출하면 모든 과정이 RaceController 내부 로직에서 진행되게 해도 될거 같은대요~. startRace()와 printWinners() 두 메서드를 나눠서 호출한 이유가 있을까요🧐?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/controller/RaceController.java
> +    private final Integer moveCount;
moveCount를 래퍼 클래스 Integer 타입으로 둔 이유가 있을까요?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/controller/RaceController.java
> +    public RaceController() {
객체의 생성자가 하는 역할은 무엇일까요? 생성자에서 다른 객체를 호출하는 게 맞을까요🧐?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/controller/RaceController.java
> +    private final CarList carList;
이 필드에는 두 가지 문제가 있어요.
1. 잘못된 이름을 사용하고 있어요. 이름이 왜 잘못되었는지는 [클린코드 2장 의미있는 이름](https://www.skullkim-dev.com/2022/01/02/2.-%EC%9D%98%EB%AF%B8-%EC%9E%88%EB%8A%94-%EC%9D%B4%EB%A6%84/)에서 답을 찾아주세요.
2. inputProcess에서 받는 값을 저장하는 필드면 지역변수로 커버되지 않을까요?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/domain/Car.java
> +    public Car(String name) {
테스트에서는 파라미터가 두 개인 생성자를, 실제 프로덕션에서는 생성자가 한 개인 생성자를 상요하고 있는대요. 이 둘을 나눠야 할 이유가 있을까요?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/domain/CarList.java
> +        cars = Arrays.stream(input.split(COMMA_DELIMITER))
map()과 collect()를 한 줄에 넣은 이유가 있을까요? 저는 아래와 같이 하는게 가독성이 더 좋아보이는대 경근님은 어떠신가요?
```java
 cars = Arrays.stream(input.split(COMMA_DELIMITER))
                .map(carName -> new Car(carName.trim()))
                .collect(Collectors.toList());
```

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/domain/CarList.java
> +                .forEach((carName) -> checkCarNameLength(carName));
이 부분을 좀 더 간결하게 바꿀 수 없을까요?
[모던 자바 인 액션 3장. 람다 표현식](https://www.skullkim-dev.com/2022/02/14/3%EC%9E%A5.-%EB%9E%8C%EB%8B%A4-%ED%91%9C%ED%98%84%EC%8B%9D/)을 보고 개선해 주세요~

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/domain/MoveCount.java
> +    private final Integer moveCount;
moveCount를 primitive type이 아닌 wraper class로 선언한 이유가 있을까요?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/controller/RaceController.java
> +        for (int i = 0; i < moveCount.getNumber(); i++) {
"욺직일 수 있는 횟수 만큼 욺직인다"는 도메인 로직 아닐까요? 도메인 로직이라면 컨트롤러에 있는게 맞을까요🧐?

2023-02-05 07:00 UTC, skullkim commented on src/main/java/racingcar/domain/Race.java
> +    private final CarList carList;
이 변수 이름의 문제는 무엇일까요?

2023-02-05 07:49 UTC, JuneK3 commented on src/main/java/calculator/Calculator.java
> +
습관이 잘못 잡혀있어서 그런지 신경쓰지 않고 넘어가게 되네요.. 수정하겠습니다.

2023-02-05 07:52 UTC, JuneK3 commented on src/main/java/racingcar/domain/CarList.java
> +        cars = Arrays.stream(input.split(COMMA_DELIMITER))
한줄에 넣지 않는게 더 나은 방식인 것 같아요. 이 부분도 제 부주의로 놓쳤네요. 바로 수정했습니다.

2023-02-05 07:58 UTC, JuneK3 commented on src/main/java/racingcar/Application.java
> +        raceController.startRace();
막연하게 경주를 진행하는 로직과 우승자를 출력하는 로직이 묶일 수 없다고 생각한 것 같아요. 확실히 메서드 하나로 내부 로직을 실행하는게 더 나을것 같네요.

2023-02-05 08:06 UTC, JuneK3 commented on src/main/java/racingcar/domain/Car.java
> +    public Car(String name) {
확실히 name 매개변수를 가지는 생성자는 불필요해보이네요.
Car 객체를 생성할때 요구사항에 맞는 난수 생성기를 기본값으로 갖게하고 싶었는데
오히려 불필요하게 복잡해진 것 같네요. 수정하겠습니다.

2023-02-05 08:28 UTC, JuneK3 commented on src/main/java/racingcar/controller/RaceController.java
> +    private final Integer moveCount;
moveCount 선언 부분을 MoveCount 클래스로 바꿨는데 코드 변경이 반영이 안되었던 것 같네요..
아래에 MoveCount의 Integer 필드부분에 남겨주신 코멘트에 답변해보겠습니다.

2023-02-05 08:30 UTC, JuneK3 commented on src/main/java/racingcar/domain/MoveCount.java
> +    private final Integer moveCount;
int형보다 Integer로 선언하는게 객체지향 방식에 가깝다고 생각했던 것 같아요.
int형과 Integer의 차이에 대해 다시 알아봤는데 null 값을 저장할 것도 아니고 Integer 클래스에서 제공하는 메소드들을 사용하는 상황도 아니어서 굳이 wrapper 클래스로 선언할 이유가 없는 것 같아요.
일단 불필요한 참조형 선언은 제거하고 int형으로 변경하겠습니다.

moveCount 값을 참조형으로 갖도록 하는 방식이 문제가 될 여지가 있을까요?? 
제가 놓친 컨벤션이 있는지도 다시 살펴보겠습니다.

2023-02-05 08:40 UTC, JuneK3 commented on src/main/java/racingcar/controller/RaceController.java
> +        for (int i = 0; i < moveCount.getNumber(); i++) {
이동 횟수만큼 움직이는 로직에 view 관련 로직이 있어서 Race 도메인에서 외부로 빼냈던 것 같아요.
도메인 객체에서 view 패키지를 의존하지 않도록 변경하면서 바꾼 부분인데 컨트롤러에서 Race 도메인 로직이 있는 것도 옳은 방식이 아닌 것 같네요. 어떤 방식으로 변경해야 할지 바로 감이 안와서 이 부분에 대해서는 좀 더 고민해보겠습니다.

2023-02-05 08:44 UTC, JuneK3 commented on src/main/java/racingcar/controller/RaceController.java
> +    public RaceController() {
객체의 생성자는 해당 객체의 필드값을 초기하하는 역할을 해야 하는 걸로 알고 있어요.
컨트롤러가 필드로 가지는 Race 객체를 초기화 하기 위해 InputProcess를 호출했던 건데 어떤 방식이 좋을지 다시 고민해보겠습니다.

2023-02-05 08:49 UTC, JuneK3 commented on src/main/java/racingcar/controller/RaceController.java
> +    private final CarList carList;
### 1.
올려주신 링크를 다시 읽고 답변해보겠습니다.

### 2.
컨트롤러가 가지는 메소드가 값을 필요로해서 필드로 저장하는 방식으로 작성했습니다.
startRace 메소드의 로직이 Race 도메인으로 옮겨지면 굳이 필드로 저장하지 않고 지역변수도 커버될 것 같아요.
startRace 메소드가 view 관련 메소드를 호출하고 있어서 어떤 방식으로 변경해야 할 지 고민이 되네요..
되도록 도메인 관련 로직은 도메인 객체가 담당하도록 변경하겠습니다. 이러면 필드로 저장하지 않아도 될 것 같아요.

2023-02-05 08:50 UTC, JuneK3 commented on src/main/java/racingcar/domain/CarList.java
> +                .forEach((carName) -> checkCarNameLength(carName));
더 간결하게 바꿀 수 있는줄 몰랐네요.. 올려주신 글 다시 읽어보고 오겠습니다.

2023-02-05 08:54 UTC, JuneK3 commented
> 안녕하세요~ 경근님~. 미션은 어떠신가요😄? 추가 리뷰 남겼어요~

여태까지 너무 생각없이 코드를 작성해왔다는 걸 느꼈고 제게 보완할 점이 아직 많다는 걸 알았어요.
2단계는 고민할 부분이 훨씬 많았습니다. 오늘 리뷰해주신 내용들도 검토해볼게요. 리뷰 감사합니다.

2023-02-06 05:40 UTC, JuneK3 commented on src/main/java/racingcar/domain/Race.java
> +    private final CarList carList;
단순 carList라는 변수만으로는 이 CarList이 의미하는바가 명확하지 않은 것 같아요.
경주에 참가하는 자동차들이라는 맥락을 추가해서 racingCarList로 변경했습니다.

2023-02-06 07:39 UTC, skullkim commented on src/main/java/racingcar/controller/RaceController.java
> +    public RaceController() {
RaceController에서 게임을 시작한 뒤 필요한 도메인을 초기화 해도 된다고 생각해 이 질문을 드린거였어요. 컨트롤러는 뷰와 도메인을 연결짓는 다리 역할을 하니 필요한 로직은 모두 컨트롤러에 있어야 한다고 생각해요.

2023-02-06 07:41 UTC, skullkim commented on src/main/java/racingcar/domain/Car.java
> +    public Car(String name) {
그럼 RandomNumberGenerator를 생성자 파라미터로 받았을 때 어떤 이점이 있을까요?

2023-02-06 07:44 UTC, skullkim commented on src/main/java/racingcar/domain/MoveCount.java
> +    private final Integer moveCount;
그건 primitive 타입과 객체 타입이 메모리에 할당 될 때 어떤 차이가 있는지를 찾아보면 답이 나올거 같네요😄. 한 번 찾아보고 결과를 알려주세요~

2023-02-06 07:44 UTC, skullkim commented on src/main/java/racingcar/domain/Race.java
> +    private final CarList carList;
위에서 읽어보라고 했던 클린코드 3장과 관련있어요~

2023-02-06 08:32 UTC, JuneK3 commented on src/main/java/racingcar/controller/RaceController.java
> +    public RaceController() {
InputProcess를 호출하는 부분을 컨트롤러 밖으로 빼냈는데 다시 수정해보겠습니다.

2023-02-06 09:08 UTC, JuneK3 commented on src/main/java/racingcar/domain/Car.java
> +    public Car(String name) {
일단 RandomNumberGenerator를 생성자 파라미터로 받으면 Car 객체의 move 메소드를 테스트하기 편해지는 것 같아요.
그리고 난수 생성 범위를 변경할수도 있어서 유지보수하기도 편할거에요.

2023-02-06 09:09 UTC, JuneK3 commented on src/main/java/racingcar/domain/Race.java
> +    private final CarList carList;
Car객체를 담는 컨테이너가 List가 아닌 CarList 클래스이니까 racingCars가 더 나은 변수명이겠네요.

2023-02-06 09:35 UTC, JuneK3 commented on src/main/java/racingcar/domain/MoveCount.java
> +    private final Integer moveCount;
primitive 타입은 스택 메모리에 할당되고 객체 타입은 힙 메모리에 할당된다고 알고 있어요.
힙 메모리에 할당된 객체 타입들은 가비지 컬렉터에 의해 제거되기까지 계속 메모리에 남아있기 때문에
primitive 타입을 사용하는 것보다 메모리 낭비가 심할것이고 가비지 컬렉터를 실행하기 위해 자원을 많이 소모하게 될 거에요.

2023-02-06 10:03 UTC, JuneK3 commented on src/main/java/racingcar/controller/RaceController.java
> +    private final CarList carList;
> 특수한 의미를 가지는 용어를 남발해서도 안된다. 여러 계정을 그룹으로 묶을때 그 변수의 이름을 accountList라 했다 하자. 여기서 List는 프로그래머에게 특수한 의미를 갖는다. 계정을 담는 컨테이너가 실제 List가 아니라면 대신에 accountGroup 또는 accounts 등으로 명명해야 한다.

Car객체들을 담는 컨테이너가 List collection이 아닌 CarList 클래스이니까 racingCars가 더 나은 변수명이겠네요.

2023-02-06 12:59 UTC, merged