[2단계 - 자동차 경주] 황의찬 미션 제출합니다.
hongik-dev-mentoring/java-racingcar pull request #6
Opened 2023-02-02 09:23 UTC by euichaan

2단계 미션 제출합니다.

Car 객체가 너무 많은 책임을 가지고 있는 것 같아서, 객체지향생활체조원칙 에 따라 원시값과 문자열을 포장했는데, 잘 한것인지 모르겠습니다..😂

추가적으로 random 값 테스트 하는것에 대한 방법을 모르겠습니다.
구글에 찾아보니 인터페이스를 이용해 테스트를 진행한 글들을 많이 봐왔는데, 그렇게 적용하면 Car 클래스의 인스턴스가 3개가 만들어져 객체지향생활체조원칙 규칙 7번에도 어긋나서 일단은 랜덤 숫자를 임의로 지정했을 때 자동차가 정지하는지, 이동하는지의 테스트만 진행했습니다.

열심히 리뷰해 주셔서 감사드립니다!

2023-02-04 02:59 UTC, skullkim requested changes
안녕하세요 의찬님~ 두 번째 단계도 잘 수행해 주셨네요😊. 질문주신 객체지향 생활체조 7번째 원칙에 대해 답변을 드리자면 저는 primitive type을 래핑한 클래스는 7 번째 원칙에서 말한 인스턴스 필드에 포함시키지 말아야 한다고 생각해요~.

객체지향 생활체조가 최초로 거론된 도서 "The ThoughtWorks Anthology"의 "Chapter 6.2 The Exercise"에서 "7. Don't use any classes with more than two instance variables"에 대한 이유를 다음과 같이 설명하고 있어요.
```
Adding a new instance variable to a
class immediately decreases the cohesion of that class.
```
즉, 인스턴스 필드를 많이 추가하면 응집도가 떨어진다는게 이유인대요. 하지만 primitive type을 래핑하는 이유는 원래 그 클래스에서 해당 primitive type이 필요하지만, 더 명확한 서술을 위해, 많아 봐야 검증 책임을 위해 한번 객체로 래핑을 하는대에 있죠. 실제로 위에서 말한 것과 같은책, 같은 챕터에서 객체지향 생활체조 3번째 원칙 "Wrap All Primitives and Strings"를 보면 다음과 같은 의견을 볼 수 있어요.
```
An int on its own is just a scalar with no meaning. When a method takes
an int as a parameter, the method name needs to do all the work of
expressing the intent. If the same method takes an hour as a parameter,
it’s much easier to see what’s happening. Small objects like this can
make programs more maintainable, since it isn’t possible to pass a year
to a method that takes an hour parameter.
```

2023-02-04 02:59 UTC, skullkim commented on src/main/java/calculator/Calculator.java
> +	private static final Pattern COMPILE_CUSTOM_SPLIT_REGEX = Pattern.compile(CUSTOM_SPLIT_REGEX);
변수명은 명사 또는 명사구여야 합니다. 그런데 'compile'은 동사죠. Pattern.compile()로 이미 컴파일을 진행 한 상태를 저장하는 것이니 'COMPILED_CUSTOM_SPLIT_REGEX'는 어떨까요🧐?

2023-02-04 02:59 UTC, skullkim commented on src/main/java/racingcar/controller/RaceGameController.java
> +		OutputView.printBlankLine();
이 메서드만 static인 이유가 있을까요?

2023-02-04 02:59 UTC, skullkim commented on src/main/java/racingcar/util/validator/NumberValidator.java
>  	private static final String MIN_ATTEMPT_NUMBER_MESSAGE = "시도 횟수는 1회 이상이어야 합니다.";
시도 횟수를 정하는 것은 도메인 로직이라는 생각이 드네요. 그런데 현재 NumberValidator를 util의 NumberGenerator에서 사용하고 있고, NumberGenerator를 Controller에서 사용하고 있네요. 이로직을 도메인으로 옮길 수 있는 방법이 없을까요🧐?

2023-02-04 02:59 UTC, skullkim commented on src/main/java/racingcar/util/generator/RandomNumberGenerator.java
> +	private static final int RANDOM_BOUND = 10;
NameGenerator, NumberGenerator 클래스 이름에서 Generator라는 단어 대신 Convertor라는 단어를 상요하면 어떨까요? RandomNumberGenerator는 내부에서 난수를 생성해 반환하기 때문에 Generator가 어울리는 것 같아요. 하지만 NameGenerator와 NumberGenerator는 값을 받아서 변환해주는 역할을 하기 때문에 Convertor가 더 적절할거 같네요😄

2023-02-04 02:59 UTC, skullkim commented on src/main/java/racingcar/domain/Cars.java
> +	public int findMaxPosition() {
findMaxPosition() 메서드를 findWinnersName()에서만 사용하고 있음에도 public으로 열고 테스트를 진행했네요. 이렇게 테스트를 진행한 이유가 있을까요?

2023-02-04 04:38 UTC, euichaan commented on src/main/java/calculator/Calculator.java
> +	private static final Pattern COMPILE_CUSTOM_SPLIT_REGEX = Pattern.compile(CUSTOM_SPLIT_REGEX);
클린 코드 2장을 읽어봤습니다! 
[클래스 이름과 객체 이름은 명사 또는 명사구를 사용하라] 라는 말이 있으므로 COMPILED_CUSTOM_SPLIT_REGEX 라는 
컴파일된 사용자 정의 분할 정규식 이름이 적합한 것 같습니다!

2023-02-04 04:41 UTC, euichaan commented on src/main/java/racingcar/controller/RaceGameController.java
> +		OutputView.printBlankLine();
static일 필요가 없었습니다! 😂 제거하고 커밋하겠습니다

2023-02-04 10:00 UTC, euichaan commented on src/main/java/racingcar/domain/Cars.java
> +	public int findMaxPosition() {
```java
@Test
	@DisplayName("가장 멀리 간 위치 찾기")
	void max_position() {
		for (int i = 0; i < 3; ++i) {
			car1.moveForward(5);
		}
		car2.moveForward(5);

		assertThat(cars.findMaxPosition()).isEqualTo(3);
	}
```
라는 테스트에서 1번를 3번, 2번 자동차를 1번 전진시킨 후 가장 많이 전진한 위치가 3임을 검증하기 위한 테스트를 작성했었습니다!

2023-02-04 10:12 UTC, euichaan commented on src/main/java/racingcar/util/generator/RandomNumberGenerator.java
> +	private static final int RANDOM_BOUND = 10;
값을 생성하는 게 아니라 Convertor 라는 이름이 더 적절할 것 같습니다! 
NameConvertor, NumberConvertor로 이름 변경하겠습니다👍

2023-02-04 17:36 UTC, euichaan commented on src/main/java/racingcar/util/validator/NumberValidator.java
>  	private static final String MIN_ATTEMPT_NUMBER_MESSAGE = "시도 횟수는 1회 이상이어야 합니다.";
AttemptNumber 클래스를 도메인에 만든 후, 검증 로직까지 이 클래스에서 진행하는 방식으로 구현했습니다!

validator 패키지는 사용하지 않게 되어 제거했습니다. 이 방식이 맞는 것인지 궁금합니다..!😭

2023-02-05 07:36 UTC, skullkim commented on src/main/java/racingcar/domain/Cars.java
> +	public int findMaxPosition() {
findMaxPosition()이라는 메서드를 Cars 내부에서만 사용함에도 외부로 드러낸다면 테스트가 프로덕션 코드에 영향을 미치는 꼴이 되므로 옳지 않다는 생각이 드네요. 또 한, "위치로 우승자를 판별한다"는 내부에 감춰야 할 기능이고 "우승자의 이름을 찾는다"가 밖으로 드러나야 할 기능이라 이 부분을 왜 테스트 해야 하는지 모르겠네요🧐. 이 테스트를 작성한 이유에 대해 알려주실 수 있나요?

2023-02-05 07:41 UTC, skullkim requested changes
의찬님~ 리뷰 잘 반영해 주셨네요. 추가 리뷰 남겼으니 확인해주세요~

2023-02-05 07:41 UTC, skullkim commented on src/main/java/racingcar/controller/RaceGameController.java
> +			OutputView.printCarsPosition(cars.getCars());
"게임 진행 가능 횟수 만큼 게임을 진행한다"는 도메인 이라는 생각이 드는대요. 그래서 컨트롤러는 "게임 진행 가능 횟수"에 대한 변화를 몰라야 한다고 생각해요. 의찬님은 어떻게 생각하시나요?

2023-02-05 07:41 UTC, skullkim commented on src/main/java/racingcar/util/generator/ForwardNumberGenerator.java
> +public class ForwardNumberGenerator implements NumberGenerator {
이 클래스는 테스트에서만 사용하고 있는대 프로덕션 패키지에 넣는게 맞을까요?

2023-02-05 07:41 UTC, skullkim commented on src/main/java/racingcar/util/generator/StopNumberGenerator.java
> +public class StopNumberGenerator implements NumberGenerator {
이 클래스도 테스트에서만 사용하고 있네요.

2023-02-06 07:05 UTC, euichaan commented on src/main/java/racingcar/domain/Cars.java
> +	public int findMaxPosition() {
1단계 요구사항 중에 모든 로직에 단위 테스트를 구현한다는 글을 읽어서 해당 테스트를 작성했었습니다!

사실 이 메서드에 관한 고민이 있었는데 
```java
public List<String> findWinnersName() {
		return cars.stream()
			.filter(car -> car.isWinner(findMaxPosition()))
			.map(car -> car.getName().getValue())
			.collect(toList());
	}
```
이 메서드에서 isWinner 메서드를 사용하고 있었습니다.
```java
public boolean isWinner(int maxPosition) {
	return position.getValue() == maxPosition;
}
```
isWinner 메서드는 다음처럼 구현되어 있습니다. 

isWinner 메서드를 테스트할 때 maxPosition에 임의로 값을 지정해준 위치가 그 자동차의 위치와 같다면 isWinner메서드는 true를 반환할 것이고, 그렇다면 저 메서드를 잘못 설계한 것이 아닌가 하는 생각이 들었습니다.

findMaxPosition을 findWinnersName()에서만 사용하게 하고(테스트를 삭제하고) private 메서드로 만든다면 내부에 기능을 감출 수 있을 것 같습니다.

이런 식으로 한다면 findMaxPosition이라는 로직은 어떻게 테스트 할 수 있을까요?

https://fishbowl.pastiche.org/2003/03/28/testing_private_methods_dont_do_it

다음과 같이 private method들은 테스트하지 않는다는 글을 봐왔어서, 
```java
private int findMaxPosition() {
		return cars.stream()
			.mapToInt(car -> car.getPosition().getValue())
			.max()
			.orElse(0);
	}
```
이 메서드를 믿고 쓸 수 있는지 궁금합니다.

2023-02-06 07:12 UTC, euichaan commented on src/main/java/racingcar/util/generator/ForwardNumberGenerator.java
> +public class ForwardNumberGenerator implements NumberGenerator {
테스트 패키지로 이동하는 것이 맞는 것 같습니다!

2023-02-06 07:12 UTC, euichaan commented on src/main/java/racingcar/util/generator/StopNumberGenerator.java
> +public class StopNumberGenerator implements NumberGenerator {
테스트 패키지로 이동시키겠습니다!

2023-02-06 11:43 UTC, skullkim commented on src/main/java/racingcar/domain/Cars.java
> +	public int findMaxPosition() {
TDD를 하는 과정을 보면 요구사항 -> 테스트 코드 작성 순으로 진행되죠. 이 말을 객체지향적으로 생각한다면 사용자가 사용할 기능이 무엇인지를 파악하고 그 기능에 필요한 책임을 가질 객체들을 찾은 후, 그 책임들을 테스트로 작성하는게 되요. 그런대, 객체들은 본질적으로 메시지를 주고 받으면서 서로에게 각자가 가질 책임을 주죠. 그럴려면 이 메시지(메서드)는 public이어야 하고요. 그래서 public으로 된 부분만 체크해도 문제 없다고 생각해요.

위 코드의 경우 "우승자를 찾는다"가 객체의 책임이 되는 거고, 그 책임을 스스로 이행하는 도중에 최대 위치가 필요한거죠.

2023-02-06 12:49 UTC, euichaan commented on src/main/java/racingcar/controller/RaceGameController.java
> +			OutputView.printCarsPosition(cars.getCars());
저도 도메인 로직이라고 생각합니다.

AttemptNumber 클래스를 Cars 클래스의 필드로 둘까 생각했는데, 그렇게 구현하면 일급 컬렉션의 정의에서 벗어나므로 시도하지 않았습니다.

Cars 일급 컬렉션과 AttemptNumber를 필드로 가지는 Racing 클래스를 만들어 자동차를 전진시켰는데, 문제는 이 도메인에서 뷰를 사용하고 있다는 점입니다..

컨트롤러가 게임 진행 가능 횟수에 관한 내용은 모르게 구현한 것 같은데, 제가 생각하기로는 게임 한 번 진행하고 그 위치를 출력하고 또 게임 한 번 진행하고 위치를 출력하고 이런식으로 이뤄지기 때문에 위치를 출력하는 View를 어떻게 분리해야할지 감이 잘 잡히지 않습니다. 

어떻게 하면 view 부분을 잘 분리할 수 있을까요..?😭

2023-02-06 12:59 UTC, merged

2023-02-06 13:06 UTC, euichaan commented on src/main/java/racingcar/domain/Cars.java
> +	public int findMaxPosition() {
좋은 글이네요.. 너무 이해가 잘 됐습니다!!