[2단계 - 자동차 경주] 이진호 미션 제출합니다.
hongik-dev-mentoring/java-racingcar pull request #9
Opened 2023-02-03 04:58 UTC by binary-ho

2023-02-04 06:21 UTC, dongho108 requested changes
안녕하세요 진호님!
2단계 진행하느라 고생 하셨습니다.
전체적으로 코드 컨벤션 같은 부분 지키려고 노력해주셔서 코드 읽기에는 좋았습니다~

domain과 view 부분에 대한 분리가 잘 안되어있는 것 같은데 이 부분 리뷰 남겼으니 참고해서 다시 제출해주시면 좋을 것 같습니다!

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Car.java
> +            position += 1;
이건 어떨까요?
```suggestion
            position++;
```

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Cars.java
> +    }
view에 대한 코드가 domain안에 들어있네요! 분리해볼까요?

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Racing.java
> +    }
여기도 view에 대한 코드가 domain에 존재하네요!

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Racing.java
> +        System.out.println(winnerString);
view 분리!

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Racing.java
> +            .append(String.join(", ", winners));
view 코드!

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/movingstrategy/AlwaysMovingStrategy.java
> +public class AlwaysMovingStrategy implements MovingStrategy {
테스트에서만 사용하는 코드인데 테스트 패키지로 옮길까요?

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Car.java
> +        if (movingStrategy.isPossibleMoveForward()) {
race에 대한 단위테스트가 없는 것 같아요!

2023-02-04 06:21 UTC, dongho108 commented on src/test/java/racingcar/CarTest.java
> +        car.race(movingStrategy);
테스트코드 안에 반복되는 코드가 많은데 포지션을 지정한다면 생성자를 이용하거나 굳이 다섯번을 호출할 필요가 없다면 한번만 두면 되지 않을까요?

2023-02-04 06:21 UTC, dongho108 commented on src/test/java/racingcar/InputRacingCarNameTest.java
> +            () -> assertThat(carNames.getCarNames().get(2)).isEqualTo("skull")
샤라웃 감사합니다 ㅋㅋ 🙇

2023-02-04 06:21 UTC, dongho108 commented on src/test/java/racingcar/RandomMovingStrategyTest.java
> +    int TO;
변수명을 대문자로 한 이유가 있을까요?

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Cars.java
> +    public static Cars getCarsFromCarNames(CarNames carNames) {
정적 팩토리 메서드 패턴을 사용하신 것 같은데 이펙티브 자바 item1의 정적 팩터리 메서드 네이밍 기준도 참고하시면 좋을 것 같아요! 검색해도 나오긴 하네요

2023-02-04 06:21 UTC, dongho108 commented on src/main/java/racingcar/domain/Cars.java
> +        cars = carNames.getCarNames()
CarNames 는 view 패키지에 있는데 도메인 클래스까지 내려와서 의존하고 있네요. 분리해볼 수 있을까요?

2023-02-05 07:39 UTC, dongho108 requested changes
2단계 리뷰 반영하느라 고생 많으셨습니다!!!
코드가 많이 좋아진 것 같아요~

몇가지 코멘트 남겼으니 의견 달아주시고 리뷰 반영후에 다시 요청해주세요!!

2023-02-05 07:39 UTC, dongho108 commented on src/main/java/racingcar/domain/Cars.java
> +    public List<Car> getCarList() {
변수나 메서드명 뒤에 자료형 `List`이 붙어있네요! 
```suggestion
    public List<Car> getCars() {
```

2023-02-05 07:39 UTC, dongho108 commented on src/test/java/racingcar/CarTest.java
> +public class CarTest {
테스트 클래스들도 연관된 클래스끼리 패키지로 묶어주시면 가독성과 유지보수가 좋아질 것 같아요~

2023-02-05 07:39 UTC, dongho108 commented on src/test/java/racingcar/RacingTest.java
> +        printCurrentRaceResult(racing);
racing test 에서 view 코드를 사용할 필요가 있을까요?

2023-02-05 07:39 UTC, dongho108 commented on src/main/java/racingcar/CarRacingService.java
>      }
service도 비즈니스 요구사항이 들어있는 domain이라고 볼 수 있어요. 현재 여기선 service 계층이 어떤식으로 사용되고있고 왜 사용하셨나요?

2023-02-05 07:39 UTC, dongho108 commented on src/main/java/racingcar/view/CarRacingResultView.java
> +    static public void printCurrentRaceResult(Racing racing) {
제어자 선언에 대해서도 컨벤션이 있습니다~ 확인해보시고 적용해주세요!

2023-02-05 07:39 UTC, dongho108 commented on src/main/java/racingcar/view/CarRacingResultView.java
> +        return new StringBuilder(car.getName())
domain의 클래스가 view에서 그대로 쓰인다면 어떤 문제가 생길 수 있을까요? (수정을 강요하는 것은 아닙니다~)

2023-02-05 07:39 UTC, dongho108 commented on src/test/java/racingcar/RangedRandomNumberPickerTest.java
> +    int to = 9;
오타인가요?
```suggestion
    int from = 0;
```

2023-02-05 09:06 UTC, binary-ho commented on src/main/java/racingcar/view/CarRacingResultView.java
> +    static public void printCurrentRaceResult(Racing racing) {
조금 감이 안 오는데 아래와 같은 형태가 되어야 할까요?

```suggestion
        cars.getCarList()
            .forEach(
                car -> System.out.println(buildCurrentPositionString(car))
            );
```

2023-02-05 09:48 UTC, binary-ho commented on src/main/java/racingcar/CarRacingService.java
>      }
CarRacingService는 Car 도메인의 도메인 서비스로 쓰이는 Racing과 View 객체에게 책임을 수행시키며 총괄(?)할 어플리케이션 서비스가 필요할 것 같아 만들었습니다.. 좋지 않은 구조일까요?

2023-02-05 09:53 UTC, binary-ho commented on src/test/java/racingcar/RacingTest.java
> +        printCurrentRaceResult(racing);
테스트를 위한 getter를 만들고 싶지 않아 이벤트 리스트를 만들어 기록할까 고민했었는데.. 
필드 2개를 유지하고 싶어 그냥 내부의 일급 콜렉션을 꺼내 확인하는 방식으로 수정해보았습니다...
Q1. 이런 테스트 방식이 올바를까요?

그리고 사실은.. 일급 콜렉션이 낯설어서 잘 쓰는 법을 모르겠습니다.
Q2. 그냥 불변성을 추구하는 단순 자료구조처럼 다루어도 되는건지..
아니면 단순 자료구조가 아닌 '객체'로 생각하여 내부 구조를 최대한 숨기며, 자율성을 높혀 줘야 하는건지 궁금합니다

2023-02-05 09:55 UTC, binary-ho commented on src/main/java/racingcar/view/CarRacingResultView.java
> +        return new StringBuilder(car.getName())
도메인 내부 구현에 종속될 수 있겠군요..

2023-02-05 13:30 UTC, dongho108 commented on src/test/java/racingcar/RacingTest.java
> +        printCurrentRaceResult(racing);
A1. 어.. 제가 질문을 제대로 이해를 못한 것 같지만 이 리뷰에 대한 제 생각을 말씀드려볼게요. 일단 view에 대한 테스트는 없어도 된다고 생각해요. view는 말씀 드렸듯이 언제든지 바뀔 수 있는 사항입니다. view가 수정될때마다 테스트를 수정해야하는 비용이 발생하니까요. 

A2. 둘 다 라고 생각하시면 될거같아요. 처음이면 낯선게 당연합니다. 일급컬렉션은 다음미션에서 사용하시면 더 와닿을거에요. 조졸두님의 블로그 글도 같이 첨부해드릴게요!
https://jojoldu.tistory.com/412

2023-02-05 13:32 UTC, dongho108 commented on src/main/java/racingcar/CarRacingService.java
>      }
말씀하신  `Racing과 View 객체에게 책임을 수행시키며 총괄(?)할 어플리케이션 서비스` 의 역할은 컨트롤러에서 하고있지 않을까요?

2023-02-05 13:33 UTC, dongho108 commented on src/main/java/racingcar/view/CarRacingResultView.java
> +    static public void printCurrentRaceResult(Racing racing) {
제어자 선언 컨벤션 말씀드린거였어요!
아래 컨벤션 `3.3. 제한자 선언의 순서` 보시면 됩니다!
https://naver.github.io/hackday-conventions-java/#modifier-order

```suggestion
    public static void printCurrentRaceResult(Racing racing) {
```

2023-02-05 13:36 UTC, dongho108 commented on src/main/java/racingcar/view/CarRacingResultView.java
> +        return new StringBuilder(car.getName())
음 그런 문제도 있는데 사실 view가 현재는 콘솔이지만, 도메인 객체가 그대로 실제 클라이언트에게 보내진다고 생각하면 클라이언트는 도메인 객체의 내부 구조를 알 수도 있다는 문제가 있을 수 있습니다!
또한 도메인 객체가 가진 정보가 수정될 수 있다는 위험도 있구요.

그래서 보통 DTO로 의존을 한번 끊어주기도 합니다!
이 리뷰는 위의 설명들을 한번 알고 넘어가시면 좋을 것 같아서 달았던 리뷰입니다~

2023-02-06 11:26 UTC, dongho108 approved these changes
리뷰 반영해주신 부분들 다 확인했습니다~

자동차 미션 하느라 정말 고생많으셨습니다.
코멘트 하나정도 남기면서 머지 하겠습니다~

다음 미션에서 뵙겠습니다.

2023-02-06 11:26 UTC, dongho108 commented on src/main/java/racingcar/CarRacingController.java
> +        while  (racing.isLeftRacing()) {
출력문은 view 클래스에 있어야할 책임같습니다!

2023-02-06 11:26 UTC, dongho108 commented on src/main/java/racingcar/CarRacingController.java
> +            printCurrentRaceResult(new CarsDto(racing.getCars()));
dto로 의존을 한번 끊어 주셨네요 ㅎㅎ 👍

2023-02-06 11:26 UTC, merged